packages:
  - packages/*
  - apps/*

catalog:
  '@cloudflare/workers-types': 4.20251115.0
  '@types/node': 22.18.6
  hono: 4.10.6
  tsdown: 0.16.4
  typescript: 5.9.3
  wrangler: ^4.47.0
  zod: 4.1.12

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
  - workerd
